In [2]:
from sklearn.linear_model import LinearRegression
import pandas as pd

In [3]:
df=pd.read_csv("Student_Marks.csv")

In [4]:
df.head(3)

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811

In [6]:
df.columns=['sinif','saat','puan']

In [7]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [8]:
y=df[['puan']]
x=df[['sinif','saat']]

In [14]:
lm=LinearRegression()
model=lm.fit(x,y)

In [11]:
#y=ax+b

In [16]:
model.coef_#kat sayı

array([[1.86405074, 5.39917879]])

In [17]:
model.intercept_#sabit

array([-7.45634623])

In [18]:
model.predict([[4,5]])

c:\Users\serkan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[26.99575068]])

In [20]:
(4*1.86405074)+(5*5.39917879)+(-7.45634623)

26.99575068

In [21]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [26]:
s1=model.predict([[3,4.508]])[0][0]

c:\Users\serkan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [29]:
-(19.202-s1)/19.202

np.float64(0.17046682485899478)

In [30]:
model.score(x,y)

0.9403656320238896